### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by outlyer** [outlyer/daily_digest#1]
- [x] Remove dependency on `wget` from `article_renderer.rb`
- [x] Remove dependency on `convert` from `article_renderer.rb`
- [x] Deal with encoding issues on sites like arstechnica.com
- [x] Deal with image issues on sites using multiple DPI images (i.e. have a `2x` in the `image` tag)
